### ISSUE TITLE
QQ小程序提交时受阻，提示需调通内容审核接口

### ISSUE THREAD

**Issue by Mushan3420** [dchijack/Travel-Mini-Program#3]
QQ小程序提交时受阻，提示因为包含评论功能，因此需要选择社交类目。
然后，按提示选择了社交类目，又提示需调通内容审核接口。

丸子小程序文档里让取消评论，但网站已经是企业备案，取消评论挺可惜的，建议把QQ的内容审核接口修复一下。

**Comment by dchijack** [comment]
内容安全审核接口目前没有办法处理，虽然提供了开发文档，但是并没有说明这个检测是如何取消的。之前做了接口测试开发网页，测试后会取消这个提示，但是现在已经不能通过了。

**Comment by dchijack** [comment]
之前做了接口测试开发网页，测试后会取消这个提示，但是现在已经不能通过了。内容安全审核接口需要后端接入，需要插件更新接入这个功能。

**Comment by Mushan3420** [comment]
> 之前做了接口测试开发网页，测试后会取消这个提示，但是现在已经不能通过了。内容安全审核接口需要后端接入，需要插件更新接入这个功能。

那就期待插件尽快更新了。正好，现在插件还有个问题：
登录后台首页，会出现
`Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /wp-content/plugins/wp-mini-program/include/dashboard.php:28` 
`Stack trace: `
`#0 /wp-admin/includes/template.php(1343): imahui_applets_dashboard_widget('', Array) `
`#1 /wp-admin/includes/dashboard.php(238): do_meta_boxes(Object(WP_Screen), 'column3', '') `
`#2 /wp-admin/index.php(148): wp_dashboard() `
`#3 {main} thrown in /wp-content/plugins/wp-mini-program/include/dashboard.php on line 28`

刷新才能消失，但下次登录还会出现。

环境信息参见 https://github.com/dchijack/Travel-Mini-Program/issues/2

**Comment by dchijack** [comment]
这个是获取仪表盘信息的时候，请求数据有误，可能是网络问题，也可能是请求数据的服务器有问题。

**Comment by Mushan3420** [comment]
> 这个是获取仪表盘信息的时候，请求数据有误，可能是网络问题，也可能是请求数据的服务器有问题。

看错误提示，是不是可以预先定义一下 object as array，来避免这个错误。
另外，内容安全审核接口既然需要更新插件，那么还是建议把插件更新一下，把这个功能做进去。
额外补充一点，春节期间更新的微信小程序版本感觉很乱，我预览了一下，没敢上线。

**Comment by dchijack** [comment]
QQ 安全接口问题不更新了，因为经过测试，目前并不能通过检测，即使用接口测试正常，提交还是会有提示接入内安审核接口，所以并没有什么用。这个问题很大关系的话，手动更新一下 GitHub 源码 include 目录里的 dashboard.php 文件替换。
